version: '3'

x-common-variables: &common-variables
  PATIENT_DATASOURCE_HOST: ${PATIENT_DB_HOST}
  PATIENT_DATASOURCE_PORT: ${PATIENT_DB_PORT}

  BOOKING_DATASOURCE_HOST: ${BOOKING_DB_HOST}
  BOOKING_DATASOURCE_PORT: ${BOOKING_DB_PORT}

  SURGERY_DATASOURCE_HOST: ${SURGERY_DB_HOST}
  SURGERY_DATASOURCE_PORT: ${SURGERY_DB_PORT}

  TRIAGE_DATASOURCE_HOST: ${TRIAGE_DB_HOST}
  TRIAGE_DATASOURCE_PORT: ${TRIAGE_DB_PORT}

  DATASOURCE_USER: ${DB_USER}
  DATASOURCE_PASSWORD: ${DB_PASSWORD}
  DATASOURCE_NAME: ${DB_DATABASE}
  REGISTRATION_SERVER: ${REGISTRATION_SERVER_HOST}
  REGISTRATION_SERVER_PORT: ${REGISTRATION_SERVER_PORT}

services:

  registration-service:
    build:
      context: .
      dockerfile: registration/Dockerfile
    ports:
      - "1111:1111"
    restart: always

  gateway-service:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - registration-service
    restart: always
    environment:
      REGISTRATION_SERVER: ${REGISTRATION_SERVER_HOST}

  patient-mysqldb:
    image: mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - patient_db_storage:/var/lib/mysql

    cap_add:
      - SYS_NICE

    
  patient-service:
    build: 
      context: .
      dockerfile: patient-service/Dockerfile
    depends_on:
      - patient-mysqldb
    ports:
      - "2222:2222"
    restart: always
    environment:
      <<: *common-variables



  booking-mysqldb:
    image: mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - booking_db_storage:/var/lib/mysql

    cap_add:
      - SYS_NICE


  booking-service:
    build: 
      context: .
      dockerfile: booking-service/Dockerfile
    depends_on:
      - booking-mysqldb
    ports:
      - "3333:3333"
    restart: always
    environment:
      <<: *common-variables



  surgery-mysqldb:
    image: mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - surgery_db_storage:/var/lib/mysql

    cap_add:
      - SYS_NICE


  surgery-service:
    build: 
      context: .
      dockerfile: surgery-service/Dockerfile
    depends_on:
      - surgery-mysqldb
    ports:
      - "4444:4444"
    restart: always
    environment:
      <<: *common-variables



  triage-mysqldb:
    image: mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - triage_db_storage:/var/lib/mysql

    cap_add:
      - SYS_NICE


  triage-service:
    build: 
      context: .
      dockerfile: triage-service/Dockerfile
    depends_on:
      - triage-mysqldb
    ports:
      - "5555:5555"
    restart: always
    environment:
      <<: *common-variables



    

  zookeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
    depends_on:
      - zookeper

volumes:
  patient_db_storage:
  booking_db_storage:
  surgery_db_storage:
  triage_db_storage: