spring:
  cloud:
    stream:
        kafka:
            binder:
                brokers: kafka:9092
        bindings:
            input:
                destination: surgery
            output:
                destination: patient-surgery
            