spring:
  cloud:
    stream:
        kafka:
            binder:
                brokers: kafka:9092
        bindings:
            input-surgery:
                destination: patient-surgery
            input-booking:
                destination: patient-booking
            output-triage:
                destination: triage
            output-surgery:
                destination: surgery
            output-booking:
                destination: booking
            